create extension if not exists pgcrypto;

create table if not exists public.auth_nonces (
  nonce text primary key,
  wallet_address text not null,
  message text not null,
  expires_at timestamptz not null,
  used_at timestamptz
);

create table if not exists public.chat_feed (
  id bigint generated by default as identity primary key,
  wallet_address text not null,
  display_name text,
  avatar_url text,
  body text not null check (char_length(body) between 1 and 300),
  created_at timestamptz not null default now()
);

create table if not exists public.chat_reactions (
  message_id bigint not null references public.chat_feed(id) on delete cascade,
  wallet_address text not null,
  emoji text not null check (emoji in ('👍','🔥','😂','😮','😢','💎','🚀','🧂')),
  created_at timestamptz not null default now(),
  primary key (message_id, wallet_address, emoji)
);

create table if not exists public.profiles (
  wallet_address text primary key,
  display_name text,
  avatar_url text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_admins (
  wallet_address text primary key,
  created_at timestamptz not null default now()
);

create index if not exists chat_feed_created_at_idx on public.chat_feed(created_at desc);
create index if not exists chat_reactions_message_id_idx on public.chat_reactions(message_id);

alter table public.auth_nonces enable row level security;
alter table public.chat_feed enable row level security;
alter table public.chat_reactions enable row level security;
alter table public.profiles enable row level security;
alter table public.chat_admins enable row level security;

do $$ begin
  create policy "chat feed public read" on public.chat_feed for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "chat reactions public read" on public.chat_reactions for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "profiles public read" on public.profiles for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  alter publication supabase_realtime add table public.chat_feed;
exception when duplicate_object then null; end $$;
